### ISSUE TITLE
От читателя 

### ISSUE THREAD

**Issue by danbestman** [AgentMC/Sao18#1]
Добрый день , я отправил вам письмо на указанную вами почту, надеюсь вы прочитаете)

**Comment by AgentMC** [comment]
Ответил, но вкратце продублирую здесь, т.к. могут быть подобные вопросы в будущем.

- Прогрессив: не планирую, его уже переводят на рулейте.
- Том 19: был бы качественный анлейт, но Дефана ещё ждать и ждать. Если по сканам, то точно не сразу после 18 ибо очень тяжело. И сканов у меня нет.
