### ISSUE TITLE
Можно ли открыть как целостную книгу?

### ISSUE THREAD

**Issue by Slumerok** [AgentMC/Sao18#4]
Можно ли через какую-нибудь программу открыть сразу как все файлы, и что бы иллюстрации были на месте?

**Comment by AgentMC** [comment]
Нет, насколько мне известно. Эти md файлы оптимизированы для веб-просмотра. 

Для этого нужно, чтобы кто-то сначала сделал рекомпиляцию в fb2/epub/doc/pdf... Согласно п.3 [лицензии](https://github.com/AgentMC/Sao18/blob/master/License.md), это может сделать кто угодно, сам я этим заниматься не буду. 

На сегодня я знаю есть docx и pdf, но там не удосужились даже сноски поправить, весьма убого сделано.
